name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore APP/PeskovHost.csproj

      - name: Publish app
        run: dotnet publish APP/PeskovHost.csproj -c Release -o app/publish

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Run Inno Setup to build installer
        run: |
          iscc installer\PeskovHostInstaller.iss
